name: Feature Request
description: Suggest an idea for this project
title: "[F]: "
labels: ["feature request"]
assignees:
  - ungiglio
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! We appreciate your input to help improve our project.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you're proposing.
      placeholder: I would like to see...
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Potential Impact
      description: How would you rate the potential impact of this feature?
      options:
        - High (Game-changing feature)
        - Medium (Significant improvement)
        - Low (Nice-to-have)
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: validation
    attributes:
      label: Final Checklist
      description: Please review and confirm the following before submitting
      options:
        - label: I have reviewed my submission for clarity and completeness.
          required: true
